# Gera PDFs fictícios (apenas para testes) com várias páginas e referências no fim.
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak

styles = getSampleStyleSheet()

PAPERS = {
    "silva2021.pdf": {
        "title": "Assistentes conversacionais em bibliotecas universitárias portuguesas: um inquérito a estudantes",
        "authors": "Ana Silva, Rui Costa e Marta Reis",
        "pages": [
            ("Resumo", "Este estudo analisa a aceitação de assistentes conversacionais (chatbots) em bibliotecas universitárias portuguesas. "
             "Aplicámos um inquérito online a 412 estudantes de três universidades do Norte de Portugal entre março e maio de 2021. "
             "Os resultados indicam que 68% dos estudantes usariam um chatbot para questões de horário e empréstimo, mas apenas 31% confiariam nele para apoio à pesquisa bibliográfica."),
            ("1. Introdução", "As bibliotecas universitárias enfrentam uma procura crescente de apoio fora do horário de atendimento. "
             "O objetivo deste trabalho é medir a intenção de uso de chatbots e os fatores que a explicam, com base no Modelo de Aceitação de Tecnologia (TAM). "
             "A pergunta de investigação é: que fatores explicam a intenção de uso de um chatbot de biblioteca pelos estudantes?"),
            ("2. Método", "Desenho transversal, com questionário de 24 itens em escala de Likert de 5 pontos, adaptado do TAM. "
             "Amostra de conveniência: 412 respostas válidas (idade média 22,4 anos; 61% mulheres). "
             "A análise usou regressão linear múltipla. A utilidade percebida e a facilidade de uso foram as variáveis independentes principais."),
            ("3. Resultados", "A utilidade percebida explicou a maior parte da variância da intenção de uso (beta = 0,52; p < 0,001). "
             "A facilidade de uso teve um efeito menor (beta = 0,21; p = 0,003). O modelo explicou 47% da variância (R2 = 0,47). "
             "Estudantes de engenharia mostraram maior intenção de uso do que estudantes de humanidades."),
            ("4. Discussão e conclusão", "Concluímos que a utilidade percebida é o fator decisivo para a adoção de chatbots em bibliotecas. "
             "As bibliotecas devem começar por serviços simples e de alto valor, como horários, renovações e reservas. "
             "Limitações: a amostra de conveniência e o desenho transversal não permitem inferir causalidade; o estudo cobre apenas o Norte de Portugal. "
             "Trabalho futuro: estudos longitudinais após a implementação real de um chatbot e comparação com outras regiões.\n"
             "References\nDavis, F. D. (1989). Perceived usefulness. MIS Quarterly.\nVenkatesh, V. (2003). UTAUT. MIS Quarterly."),
            ("", "Lee, K. (2019). Chatbots in academic libraries. Library Hi Tech.\nSmith, J. (2020). AI services. JAL."),
        ],
    },
    "garcia2023.pdf": {
        "title": "Library chatbots after deployment: a qualitative study with librarians in Spain",
        "authors": "Lucía García and Tomás Ortega",
        "pages": [
            ("Abstract", "This paper examines how librarians experience chatbots after deployment in Spanish university libraries. "
             "We conducted 18 semi-structured interviews with librarians from six universities in 2022. "
             "Librarians reported reduced repetitive queries but raised concerns about accuracy and user trust."),
            ("1. Introduction", "Most studies on library chatbots measure student intentions before deployment. "
             "Our aim is to understand the post-deployment experience from the librarians' perspective. "
             "Research question: how do librarians perceive the impact of chatbots on reference work?"),
            ("2. Methods", "Qualitative design with thematic analysis (Braun and Clarke). Purposive sample of 18 librarians (12 women, 6 men) "
             "from six Spanish universities that had used a chatbot for at least one year. Interviews lasted 45 to 70 minutes and were coded in NVivo."),
            ("3. Findings", "Three themes emerged. First, chatbots handled about 40% of routine questions, freeing time for complex reference work. "
             "Second, librarians distrusted chatbot answers to research questions, citing incorrect references generated by the system. "
             "Third, students rarely used the chatbot for literature searches, preferring human help."),
            ("4. Conclusion", "Chatbots are useful for routine services but not yet reliable for research support. "
             "Limitations: small sample, only Spanish institutions, and no student data. "
             "Future research should combine librarian and student perspectives and test chatbots with verified sources.\n"
             "References\nBraun, V., & Clarke, V. (2006). Thematic analysis. QRP.\nSilva, A. (2021). Assistentes conversacionais."),
        ],
    },
}

for fname, p in PAPERS.items():
    doc = SimpleDocTemplate(fname, pagesize=A4)
    story = [Paragraph(p["title"], styles["Title"]), Paragraph(p["authors"], styles["Normal"]), Spacer(1, 12)]
    for i, (h, t) in enumerate(p["pages"]):
        if i > 0:
            story.append(PageBreak())
        if h:
            story.append(Paragraph(h, styles["Heading2"]))
        for para in t.split("\n"):
            story.append(Paragraph(para, styles["BodyText"]))
    doc.build(story)
    print("gerado", fname)
